sudo: required
language: bash
services: docker
env:
  matrix:
  - VERSION=stable VARIANT=alpine
  - VERSION=stable VARIANT=debian
  - VERSION=testing VARIANT=alpine
  - VERSION=testing VARIANT=debian
  - VERSION=legacy VARIANT=alpine
  - VERSION=legacy VARIANT=debian
  - VERSION=snapshot VARIANT=alpine
  - VERSION=snapshot VARIANT=debian
  global:
  - secure: q9qhGDxJU5WOTq6MIsPwd7kZe7Ue/YjAmWTpnrMIBhirVZt4UzInw+xlyxJc/yyqzyB9+712MtT3ePSnpo2MtxiHUIcBgBJ+eFE7OqFZ9KG04wUe1lat8HkhvhxPxLD1wRR10bFIpXPPrnnHXLCkbGC/7YAFxDDB44mv0+kZc3mKeO8qjrPSpQgyh/yZYEtOVMb+sCJ314BXIBocHKbSdpaXlYdblueDVz1y/4lJjtiNxRrupTADM4uurPMz5GutUwbJs3i+VPNDX5wREuJeoSjwl6jE07QhW67ExIgG1CDSJyC1QJzaT/atXJwXOIX/wv5fOdM+RKz2V5ZwoH7GiLIrrPYymRzI32xfsKmUEyIbs2TrbjIlEZ+bCYJ8furCGf0UdQu1PsVUUaT3w9ZOhKJuExh9gAqAH9G/7fvu8y4cJKlJqavtpNMjM4kmTqUN1/vLaIIkgWodpMXiQMta7oZ8unCHpQMOlQlci+M0GKy1Vd6zZUYS/Cd2FakCDNmg7JmjgmniTAGp86+PV2hmPt/jZAwmNZQtmQ585kKFwuH3HInPXAqEJ03Hk22BHFJvXQUr3zu1IEKmQ9HthUW3CTwiPdBD9jsh7mtgM1jwTqgIKQi3aoEIdV7JAENTNf+D/u7ZZTer7rLOuTgYABHytzpzSqsImDyVqimej2yxU7A=
  - secure: eSVIkgmOUliqFE5ix4+h32VyTjBi1+N2mypZJsMKV6x1CluQJqzy6KIMqq5smYqm9ebbDP7olnM2l5bFts9i6FnndcWvI97JKY/i+M5fwi6jtN7kdDxE07B2a2TSY9QWmhyrIoCUxMxsO83fWoU1YogdwHb6450acygD5+fNZnYJjshrIiYqGgS+xw+rj/wHOldw7V5bMD0ZY+Yl8o/T4MJtXlfiMnhpQwY87aHyMYSuTZmBDfbFV7tpZoDOpkHpKyzb+8r+ctk7x2mBcvwiKD4vhhpEdZ8GP7WvhzUT+AywKF7hPJIQ8I1IKnq219os2skfNQpQZoYVn4dr+NSiC+9sYDMxiUtQWBy/VC/j/byDuuqNqVaUoLHdggYOm+EzTtPaEHTUfLEP2M26ARJvu+jkNeuynWBKF7ZorLeUeOJpYn+JOaGb7QNT5kUO+Y8puzArxwAj5lNNhaVZk7WU6kEhDgkD5IA0J8i4gsfGdfuaHrQXfAVXyjxANxii+M+HUwZAXQByuij78e421YmWMrGFalYctbNNYx/f2WlXO55iw0L+JU0sDVR8FdU3dZErrD/OTnIgPqBHqw0ftFKzgHesaDegOYnt4WX7eraD6duuf7CHjySHPp9Bz3EDXRKioqLnMXfzOOKSDYRKIMLcK5tyonpNFCdATUTzdqCBv6I=
  - secure: EGEHsgiSjEknCvgnyCmGxTlet9jqS4Em/XjxgZEPnhvLVa9uJlRTdNXOrBqm+hg3Har044Dt/v+vVDUOFu59fWZEWSspKtq5VxEeK8SB3UUvaVjxy/kyz7ncrRd5Lkv12yYJxvCnOp47ZxIvpDgxUkxKG3bOtGuHGOvLieERTaHvGZ9KBIhUT6WJXq+mZYb4OjtUhhGpfxFnsxDDsvNtDf3a7mueldgfCWIuowVCwTE/x7bzhoEAvtTvUpQz4DdDBlwdwArYlMxv1v3NMv2ONMTlMvXKWL0Sl1CWCjUWOyX7P5SWYMkRC5meEmqAANQW4zbh3kwOH1s0tX+xeo016rqGii3Qj5Cv2M0I23r8+QWxgPjXVpy+CHzoGQJXUr8QvIgTuRoqxJnMhrh72+VmEEpeWrV+1Igune9BSGQO7jNd0e4fSqfUcVI+SC/QnKUitKiWWC0XLQsaHThXt/Fo60BZLvjOM4KuMatYJu/ePPL7Y4YuxQtyXxqFY2+kGkMcM8JBDeClyY7Qkh9a4iYZ8wFX+TJAJZDIyLQIRh510id7TIZMJJPNWcGwAYZnTA5/rYheTEmLWPR+sCaDpTu1azXl4yV3XwR3IgUw4PWzSTilk0dTvbIDDFRWGIi2zS7/qYPkgxOtPGoYB/LRNtUccSFMoPpxC80lcaCOfYmCGqw=
branches:
  only:
  - master
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
before_script:
- env | sort
- image="kynothon/multiplane:${VERSION}-${VARIANT:-ubuntu}"
script:
- docker build -t "${image}" --build-arg MAKEFLAGS="-j$(($(grep -c ^processor /proc/cpuinfo)
  + 1))" docker-images/${VERSION}/${VARIANT}
after_script:
- docker images
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker push ${image}
